print('-' * 30)
print(f'{"VARIAVEIS":^30}')
print('-' * 30)
nome = str(input('Digite o nome de um funcionário: '))
empresa = str(input('Digite a instituição: '))
qtde_funcionarios = int(input('Digite a quantidade de funcionários: '))
mediaMensalidade = float(input('Digite a média da mensalidade: '))
print('-' * 30)
print(f'{nome} trabalha na empresa {empresa}')
#print('{} trabalha na empresa {}'.format(nome, empresa))
print(f'Possui: {qtde_funcionarios} funcionarios.')
print(f'A média da mensalidade é de: R$ {mediaMensalidade}.')